import type { Vehicle } from '../types/vehicle';
import { urlToDataUrl } from './imageUtils';

function downloadTextFile(filename: string, contents: string, mimeType: string) {
  const blob = new Blob([contents], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

/** Vehicles with every image resolved to a self-contained data: URL, ready to embed in source code. */
async function withEmbeddedImages(vehicles: Vehicle[]): Promise<Vehicle[]> {
  return Promise.all(
    vehicles.map(async (v) => ({
      ...v,
      image: await urlToDataUrl(v.image),
    })),
  );
}

export async function exportVehiclesAsJson(vehicles: Vehicle[]) {
  const withImages = await withEmbeddedImages(vehicles);
  downloadTextFile('vehicles.json', JSON.stringify(withImages, null, 2), 'application/json');
}

export async function exportVehiclesAsTs(vehicles: Vehicle[]) {
  const withImages = await withEmbeddedImages(vehicles);
  const body = JSON.stringify(withImages, null, 2);
  const contents = `// Generated by the admin panel — replace src/data/vehicles.ts with this file
// to make your changes permanent in the codebase.
//
// Photos are embedded as base64 data URLs below (same approach as the
// original single-file prototype). That keeps this file self-contained,
// but makes it large — if you'd rather keep photos as separate files,
// swap the relevant "image" lines below back to
// "import someImg from '../assets/some-file.jpeg'" and reference someImg.

import type { Vehicle } from '../types/vehicle';

export const vehicles: Vehicle[] = ${body};

export function getVehicle(key: string): Vehicle | undefined {
  return vehicles.find((v) => v.key === key);
}
`;
  downloadTextFile('vehicles.ts', contents, 'text/typescript');
}
